[build]
  base = "."
  publish = "frontend/build"
  command = "npm install -g cross-env && cd frontend && npm install && npm run build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"

# Frontend routes
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Backend API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Catch-all for frontend routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "backend"
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]
  format = "esm" 